[project]
name = "hypixel-bazaar-flipper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.4",
    "rich>=14.0.0",
    "textual>=3.6.0",
]
